version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: app
    command: [ "./main", "--host=0.0.0.0", "--port=8082" ]
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  db-data: